SciPy


In [3]:
#numpy

import numpy as np 

aArray = np.ones((3,3))
aArray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
from scipy import linalg
arry = np.array([[1,2],[3,4]])
linalg.det(arry)

-2.0

NDARRAY


In [11]:
aArray = np.array([1,2,3])
aArray

array([1, 2, 3])

In [13]:
bArray = np.array([(1,2,3),(4,5,6)])
bArray

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
bArray.ndim

2

In [15]:
bArray.shape

(2, 3)

In [16]:
bArray.size

6

In [17]:
bArray.dtype

dtype('int32')

In [18]:
bArray.itemsize

4

In [22]:
np.arange(1,9,.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5])

In [23]:
np.random.random((2,2))

array([[0.83437127, 0.91715376],
       [0.44219835, 0.85206366]])

In [24]:
np.linspace(1, 2, 10, endpoint=False)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [25]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.zeros((2,2)) 

array([[0., 0.],
       [0., 0.]])

In [27]:
np.fromfunction(lambda i,j:(i+1)*(j+1), (9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])